services:
  db:
    image: postgres:16-alpine
    container_name: app_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db_psql_library}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6
    volumes:
      - mongodata:/data/db
    # ports:
    #   - "27017:27017" # décommente si tu veux accéder depuis l'hôte

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - ./.env.docker
    environment:
      APP_ENV: docker
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-app}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-app}
      DB_NAME: ${POSTGRES_DB:-db_psql_library}
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB: miel_des_mots
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      MAIL_SERVER: mailpit
      MAIL_PORT: 1025
      MAIL_USE_TLS: "false"
      MAIL_USE_SSL: "false"
      MAIL_DEFAULT_SENDER: "La Plume des Étoilées <no-reply@laplumedesetoilees.fr>"
      FLASK_APP: "app:create_app"
      PYTHONUNBUFFERED: "1"
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_started
      mailpit:
        condition: service_started
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  db_data:
  mongodata:
